### ISSUE TITLE
Set dependencies version 

### ISSUE THREAD

**Issue by victorynox** [ReputationVIP/queue-client#15]
In composer.json set dependencies version by [Caret Version Range](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)
Because selected version [composer.json](https://github.com/ReputationVIP/queue-client/blob/master/composer.json#L11) breaks compatibility if symfoni is updated major vesion.

**Comment by tejerka** [comment]
Don't hesitate if you can create Pull Request to fix it.
I will take a look ASAP.
